server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://120.79.18.137:3306/uums?characterEncoding=utf8
    username: root
    password: MYh1000s23t14V
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: druidDataSource